### ISSUE TITLE
[Minério] Calcita

### ISSUE THREAD

**Issue by dellanoderek** [WaldsonLima/ForgeRevolutionV1#17]
Efeito: Invisibilidade
Locais: Jardim Pálido

**Check-list**

- [x] Criar arte do item (Calcita)
- [x] Criar código do item (Calcita)
- [x] Criar arte 2D do bloco minério (Bloco Minério Calcita)
- [x] Criar código do item (Bloco Minério Calcita)

**Comment by WaldsonLima** [comment]
A ideia inicial era que esse minério seria encontrado no novo bioma, o pale garden, mas a tag desse bioma ainda não está disponível para criação de add-ons, então o local para achar esse minério passou a ser as ilhas cogumelo.
